In [1]:
import numpy as np

In [6]:
a = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
b = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(a + b)

[[2 1 1]
 [2 3 2]
 [3 3 4]]


In [7]:
import numpy as np
A = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
B = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(A + B)

[[2 1 1]
 [2 3 2]
 [3 3 4]]


In [11]:
A=np.array([[1,1,1],[2,2,2],[3,3,3]])
B=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(A.dot(B))

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [12]:
dic = {}
name = input()
height = eval(input())
dic['name'] = height

print('小明', dic.get('小明'))