## 方差  
### 定义
方差表示随机变量的离散程度，即每个可能值与平均值之间的偏离程度。
### 公式
Var(X) = [(X - E(X))^2] /（n-1）

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams["font.family"] = "SimHei"
plt.rcParams["axes.unicode_minus"] = False
plt.rcParams["font.size"] = 12

x = np.array([1, 8, 6, 4, 10, 7])
# 将x的均值变为0
x = x - x.mean()
# ddof:Delta Degrees of Freedom 用来设置方差分母的偏差数值，默认为0， 这里设置为1（为了无偏估计）
print(np.var(x, ddof=1)) # F1
# 这里不用对x转置
print(np.dot(x.T, x) / (len(x)-1)) # F2

10.0
10.0


## 协方差
### 定义
用来衡量两个随机变量X和Y之间的相关程度，协方差越大，则X和Y变化趋势越一致。   
  说明：当协方差的俩个随机变量是同一个随机变量时，协方差等于自身的方差.   
    协方差为零，两个方程线性不相关
### 计算
协方差 = ∑(Xi - Xm) * (Yi - Ym) / (n-1) 

In [2]:
x = pd.Series([1, 2, 3, 4, 5, 6])
y = pd.Series([2, 4, 6, 8, 10, 12])
x = x - x.mean()
y = y - y.mean()
print(x.cov(y)) # pd.cov() 求协方差
print(np.dot(x.T, y) / (len(x) - 1))

7.0
7.0


## 协方差矩阵  
### 定义  
协方差矩阵用来存储多个随机变量两两之间的协方差。设随机变量X1, X2, X3......., 矩阵C的定义为：  
$
C=
\begin{bmatrix}
c_{11}&c_{12}&...&c_{1n}\\
c_{21}&c_{22}&...&c_{2n}\\
...&...&...&...\\
c_{n1}&c_{n2}&...&c_{nn}\\
\end{bmatrix}
$  
$
c_{ij}=Cov(X_i, X_j)
$  
$  
则矩阵C就是n个随机变量X_1，X_2，X_3，...,X_n的协方差矩阵
$  
说明：  
协方差矩阵是对称矩阵  
协方差矩阵主对角线上的元素为各个随机变量的方差

C=$\frac{1}{m-1} X^TX$


In [3]:
np.random.seed(0)
X = np.random.random(size=(4, 3))
X = X - X.mean(axis=0)
# rowvar:矩阵是否用行来表示，默认为True(是否用一行来表示一个特征)
print(np.cov(X, rowvar=False, ddof=1))
print(np.dot(X.T, X)/(len(X)-1))

[[ 0.00668685 -0.01128197 -0.00164677]
 [-0.01128197  0.04055432  0.01622402]
 [-0.00164677  0.01622402  0.03677116]]
[[ 0.00668685 -0.01128197 -0.00164677]
 [-0.01128197  0.04055432  0.01622402]
 [-0.00164677  0.01622402  0.03677116]]


## 矩阵乘法的几何意义
当矩阵A与向量$\vec{v}$相乘时，实际上，是对$\vec{v}$进行线性变换。  
这里我列出常用的两种线性变换  
1.对向量进行旋转  
2.对向量进行缩放

### 旋转变换

In [4]:
# 向量v与x轴的夹角为pi/4, 即45度
v = np.array([4, 4])
# 旋转弧度
theta = 1 / 6 * np.pi
A = np.array([[np.cos(theta), -np.sin(theta)],
             [np.sin(theta), np.cos(theta)]])
v2 = np.dot(A, v)
print(v2)

[1.46410162 5.46410162]


In [ ]:
def plot_point(*points):
    for point in points:
        plt.plot(*point)

plt.figure(figsize=(5, 5))
# 定义原点
origin = (0, 0)
# 绘制原点以及向量的终点，以确保向量能正常显示。
plot_point(origin, v, v2)
# 坐标轴等比例显示
